# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
    - task: UseDotNet@2
      inputs:
        version: '3.0.x'
        packageType: runtime


    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        version: 3.0.x
        performMultiLevelLookup: true

    # do this before your build tasks

    - task: UseDotNet@2
      inputs:
        command: restore
        projects: '**/*.csproj'
        feedsToUse: config
        nugetConfigPath: NuGet.config    # Relative to root of the repository
        externalFeedCredentials: <Name of the NuGet service connection>
    # ...


    - task: UseDotNet@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release' # Update this to match your need

    - task: UseDotNet@2
      displayName: 'Install dotnetsay'
      inputs:
        command: custom
        custom: tool
        arguments: 'install -g dotnetsay'

    - task: UseDotNet@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'myWebsiteName'



    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
